### PR TITLE
Update footer.html

### PR DESCRIPTION
**Pull request by allalala**
Added social media links

### CODE REVIEW

**Comment by stvnrlly** [comment]
Do we plan to keep the other social icons?

**Comment by gemfarmer** [comment]
@allalala if we don't plan to keep the other social icons I can remove them and redesign accordingly.

**Comment by allalala** [comment]
@gemfarmer @stvnrlly Yes, the client really liked the social icons.
The client would like the Facebook, YouTube, Twitter, and mail icons. The mail icon should link `mailto:` to an email address that is currently TBD. 

However, we can safely remove the Instagram and Pinterest icons.

**Comment by stvnrlly** [comment]
:+1:

**Pull request merged**
