### PR TITLE
ability to add a few different agencies

### PR DESCRIPTION
**Pull request by stvnrlly**
Since the data provided is so different, this takes the not-super-ideal approach of customizing the loading script for those different agencies.

All of the data has also been snapshotted as a fixture, in `forecast/data/multi-agency.json`. The instructions in `README.md` have been updated with loading instructions.

### CODE REVIEW

**Comment by lauraGgit** [comment]
See my line note about the readme. I can make the change if you'd like and then merge this.

**Comment by lauraGgit** [comment]
Also, the State Dept. data, uses the State filter to post what countries the opportunity is in.

**Comment by lauraGgit** [comment]
Also, viewing the individual detail pages. i.e. Below, it will break the page if there is a noneType for a value. I haven't found this on another page, but it could use some sort of catch.
http://0.0.0.0:8000/details/4802

**Comment by stvnrlly** [comment]
I'm glad you found that page; I'll add an `if` block for that part of the template. There may be some other fields that should disappear if empty, as well.

**Comment by lauraGgit** [comment]
I think you are good now.

**Pull request merged**
